# AdventureCraft Core Plugin

# Mob Setting
# This distance will determine the level of the mob, >250 = Normal mob no level. <250 = Level 1, <500 = level 2 etc.
Distance_Threshold: 250
Health_Multiplier: 15
Damage_Multiplier: 5
# Boss mobs attribute will be multiplied further by this amount.
Boss_Multiplier: 10
Max_Health: 2048
Max_Damage: 2048

Worlds:
  - world

Drop_Chance:
  Tipped_Arrow: 5
  Dungeon_Key: 1
  Scroll: 5
  Normal: 15
  Custom: 100
  Skill: 5

Chest_Book: 8
Chest_Scroll: 10
Chest_Scroll_Max: 5
Chest_Arrow: 10
Chest_Arrow_Max: 5

OPEN_AI_KEY: ""