# AdventureCraft Core Plugin

# Mob Setting
# This distance will determine the level of the mob, >250 = Normal mob no level. <250 = Level 1, <500 = level 2 etc.
Distance_Threshold: 250
Health_Multiplier: 15
Damage_Multiplier: 5
# Boss mobs attribute will be multiplied further by this amount.
Boss_Multiplier: 10
Max_Health: 2048
Max_Damage: 2048

Worlds:
  - world

Drop_Chance:
  Tipped_Arrow: 5
  Dungeon_Key: 1
  Scroll: 5
  Normal: 15
  Custom: 100
  Skill: 5

Chest_Book: 8
Chest_Scroll: 10
Chest_Scroll_Max: 5
Chest_Arrow: 10
Chest_Arrow_Max: 5

OPEN_AI_KEY: ""
MODEL: ""

## WIll contain all quest related settings that we can control
Quest_Settings:
  ## How often each player will try to request a new Quest
  Frequency: 2000
  ## The duration requirement, player with session duration higher than this will have a possibility of getting those rank quest
  Rank_Requirement:
    Common: 3600
    UnCommon: 21600
    Rare: 43200
    Epic: 86400
    Legendary: 259200
    Mythical: 432000
    Fabled: 604800
    Godlike: 1209600
    Ascended: 2592000